parameters: 
services: 
    tactics.twig.object_table_extension:
        class: Tactics\TableBundle\Twig\TableExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
        
    tactics.table.factory:
        class: Tactics\TableBundle\TableFactory
        arguments: [@service_container]
